# Generated by Django 3.1.1 on 2020-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbRestApi', '0013_auto_20200912_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
